---
- name: Install Docker using Ansible
  hosts: target
  become: true
  become_method: sudo
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
      become: true
    - name: Install Git
      ansible.builtin.apt:
        name:
          - git
        state: present
