---
- name: Install Docker using Ansible
  hosts: target
  become: true
  become_method: sudo
  vars:
    ansible_become_password: osboxes.org
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
      become: true
    - name: Install prerequisites for Docker
      ansible.builtin.pat:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      become: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: yes

    - name: Add Docker repository
      apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable'
        state: present
      become: yes

    - name: Update APT package cache after adding repository
      apt:
        update_cache: yes
      become: yes
    - name: Install Docker
      apt:
        name:
          - docker-ce
          - d
        state: present
      become: yes
      async: 300
      poll: 0
    - name: Wait for Docker installation to complete
      wait_for:
        path: /usr/bin/docker
        state: present
      register: docker_install_result
      retries: 300
      delay: 5

    - name: Display Docker installation result
      debug:
        var: docker_install_result
