---
- name: Execute Python Script File and Capture Stdout
  hosts: target
  tasks:
    - name: Make tmp directory if not found
      command: mkdir /home/osboxes/tmp creates=/home/osboxes/tmp
    - name: Transfer Python Script File
      copy:
        src: ./app.py
        dest: /home/osboxes/tmp/app.py
        mode: '0755'
    - name: Make Script Executable
      file:
        path: /home/osboxes/tmp/app.py
        mode: '0755'
    - name: Run Python Script File
      command: /home/osboxes/tmp/app.py
      register: script_output
    - name: Display Script Output
      debug:
        var: script_output.stdout
