---
- name: Install git
  hosts: target
  become: true
  become_method: ansible.builtin.sudo
  vars:
    ansible_become_password: osboxes.org
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
      become: true
    - name: Install Git
      ansible.builtin.apt:
        name: git
        state: present
      become: true
      async: 1000
      poll: 0
      register: install_result
    - name: Wait for Git installation to complete
      ansible.builtin.wait_for:
        path: /usr/bin/git
        state: present
      register: install_result
      retries: 300
    - name: Display Git installation result
      ansible.builtin.debug:
        var: install_result
