---
- name: Install git
  hosts: target
  become: true
  vars:
    ansible_become_password: osboxes.org
  tasks:
    - name: Clone a repo
      ansible.builtin.git:
        repo: 'https://github.com/iamstarcode/cat-wiki-api-express.git'
        dest: /home/osboxes/hellowordl/repo
