---
- name: Working with vars
  hosts: target
  vars:
    hello: 'Hello World!'
  vars_files:
    - vars.yml
  tasks:
    - name: Print the mutliplication by 2
      ansible.builtin.debug:
        msg: '{{ value | int * 2 }}'
