---
- name: Install Nvm in host machine
  hosts: target
  tasks:
    - name: Do somethong first
      ansible.builtin.shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
      args:
        creates: '{{ ansible_env.HOME }}/.nvm/nvm.sh'
    - name: Install node 18
      ansible.builtin.shell: nvm list
      register: cmd_output
    - name: Display Script Output
      debug:
        var: cmd_output.stdout
