---
- name: Pull Docker Images using Ansible
  hosts: target
  become: true
  become_method: ansible.builtin.sudo
  vars:
    ansible_become_password: osboxes.org
  tasks:
    - name: Pull Docker images
      community.docker.docker_image:
        name: '{{ item }}'
      loop:
        - ubuntu:latest
        - nginx:latest
        - alpine:latest
      become: true
