---
- name: Execute Python Script File and Capture Stdout
  hosts: target
  tasks:
    - name: Transfer Python Script File
      ansible.builtin.copy:
        src: ./app.py
        dest: $HOME/app.py
        force: true
        mode: '755'
    - name: Run Python Script File
      ansible.builtin.command: python3 $HOME/app.py
      register: script_output
      changed_when: script_output != 0
    - name: Display Script Output
      ansible.builtin.debug:
        var: script_output.stdout
