---
- name: Install Apt packages
  hosts: target
  become: true
  vars:
    pkgs:
      - git
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
      become: true
    - name: Install packages
      ansible.builtin.apt:
        name: '{{ pkgs }}'
        state: present
