---
- name: Setup Nginx on EC2
  hosts: web
  become: true

  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
    - name: Install Nginx
      ansible.builtin.apt:
        name:
          - nginx
        state: present
    - name: Start Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
    - name: Allow Nginx HTTP
      community.general.ufw:
        rule: allow
        name: 'Nginx HTTP'
